### ISSUE TITLE
chef-api 0.9.0 on rubygems misses the templates directory

### ISSUE THREAD

**Issue by rmoriz** [chef/chef-api#71]
for example:

```shell
# 0.9.0 (missing)
curl https://rubygems.org/downloads/chef-api-0.9.0.gem | tar xv && tar xfvz data.tar.gz && ls -la

# 0.8.0 (with templates)
curl https://rubygems.org/downloads/chef-api-0.8.0.gem | tar xv && tar xfvz data.tar.gz && ls -la
```

The missing templates cause the following error in a production setup:

```shell
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/chef-api-0.9.0/templates/errors/http_forbidden_request.erb
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/chef-api-0.9.0/lib/chef-api/errors.rb:26:in `read'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/chef-api-0.9.0/lib/chef-api/errors.rb:26:in `message'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1123:in `handle_exception!'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1097:in `rescue in dispatch!'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1096:in `dispatch!'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
        /Users/rmoriz/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
```

**Comment by rmoriz** [comment]
Just found a renamed version 0.9.1 at  https://rubygems.org/downloads/chef-infra-api-0.9.1.gem which seems to be complete. Maybe admins can rename this repo and update the changelog? Thank you :)

**Comment by tas50** [comment]
0.10 of both named gems are up and they both include the templates dir. Thanks for the report
